const app=(()=>{
const KEY='sao_workplace_v1';
const FILE_DB='sao_workplace_files_v1';
const CATEGORIES=['Home','Doctor / Clinical','Clinic Management','Office / Administration','Student / Study','Research','App Development & AI','App Development','Banking & Insurance','Family Responsibility','Friends / Social','Health & Fitness','Spiritual / Sadhana','Travel / Seminar','Blogging / Content','Finance / Purchase','Other'];
const PRIORITIES=[{value:'Red',label:'Red • Critical / Do First'},{value:'Orange',label:'Orange • High'},{value:'Yellow',label:'Yellow • Important'},{value:'Green',label:'Green • Routine / Low'}];
const STATUSES=['Idea / Capture','Start Today','Started Today','Work Started','Will Start Soon','Done','Pending','Need Modification','Need More Suggestion','Need Help to Run','Waiting','Need to Stop','Stopped'];
const HORIZONS=['Today','Tomorrow','2-3 Days','1 Week Later','1 Month Later','3 Months Later','6 Months Later','1 Year Later','Someday / No Date','Custom Date'];
const SOURCE_TYPES=['Online Course','Offline Course','Book','Article / Journal','YouTube','Seminar','Webinar','Guru / Mentor','Friend / Colleague','Clinical Experience','My Notes PDF','My Notes Printout','Other'];
const TRAVEL_STATUSES=['Idea','Planning','Ticket Pending','Ticket Booked','Confirmed','In Progress','Completed','Postponed','Cancelled'];
const defaultSettings={appName:'SAO Workplace for Office & Home',ownerName:'Dr Rajesh Sao',dailyJapaTarget:5000,weekStarts:'Monday',theme:'Soft Blue'};
const WORKSPACES={
  home:{label:'Home',icon:'🏠',color:'home',categories:['Home','Family Responsibility','Friends / Social','Health & Fitness','Spiritual / Sadhana','Banking & Insurance','Finance / Purchase'],quickCategory:'Home',subtitle:'Family, personal responsibilities, health, finance and home planning.'},
  clinic:{label:'Clinic / Office',icon:'🩺',color:'clinic',categories:['Doctor / Clinical','Clinic Management','Office / Administration'],quickCategory:'Clinic Management',subtitle:'Clinical work, clinic management, administration and office responsibilities.'},
  study:{label:'Study',icon:'📚',color:'study',categories:['Student / Study','Research'],quickCategory:'Student / Study',subtitle:'Study topics, research work, learning sources and deadlines.'},
  ai:{label:'App Development & AI',icon:'🤖',color:'ai',categories:['App Development & AI','App Development'],quickCategory:'App Development & AI',subtitle:'Apps, websites, AI experiments, GitHub work and technology projects.'}
};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||{tasks:[],study:[],wellness:[],travel:[],settings:defaultSettings};
db.tasks=db.tasks||[];db.study=db.study||[];db.wellness=db.wellness||[];db.travel=db.travel||[];db.settings={...defaultSettings,...(db.settings||{})};db.reflections=db.reflections||[];db.tasks=db.tasks.map(t=>({estimatedMinutes:0,nextAction:'',waitingFor:'',waitingContact:'',repeat:'None',focus:false,progress:t.status==='Done'?100:0,...t}));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const today=()=>new Date().toISOString().slice(0,10);const fmt=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'-';
const isDone=t=>t.status==='Done';const priorityRank=p=>({Red:1,Orange:2,Yellow:3,Green:4}[p]||9);const horizonRank=h=>HORIZONS.indexOf(h)<0?99:HORIZONS.indexOf(h);const tpl=id=>document.getElementById(id).content.cloneNode(true);
function fillOptions(el,items,blank=false,blankText='Select'){el.innerHTML=(blank?`<option value="">${blankText}</option>`:'')+items.map(x=>{const v=typeof x==='string'?x:x.value,l=typeof x==='string'?x:x.label;return `<option value="${esc(v)}">${esc(l)}</option>`}).join('')}
const titles={dashboard:['Dashboard','Your work, study, health, family and life responsibilities in one place.'],
  myday:['My Day','Focus on what truly needs attention today.'],tasks:['Tasks & Projects','Capture, prioritize, schedule and finish responsibilities.'],
  board:['Status Board','A visual flow of ideas, active work, waiting and completion.'],study:['Study Planner','Plan what to learn, from where, when and how much.'],wellness:['Wellness & Sadhana','Track health habits, spiritual practice and seva.'],travel:['Travel & Seminar','Plan purpose, tickets, time, budget and nearby visits.'],review:['Review Center','Daily, weekly and monthly review of forgotten and blocked work.'],ai:['AI Insights','Smart local analysis, focus strategy and future-ready decision support.'],
  summary:['Master Summary','A single review of everything requiring your attention.'],files:['Files & Notes','Keep supporting documents linked to tasks and life areas.'],backup:['Backup / Restore','Protect your workplace data and move it between devices.'],settings:['Settings','Personal targets and app preferences.']};
function showView(name){
  try{
    const meta=titles[name]||titles.dashboard;
    $$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));
    $('#pageTitle').textContent=meta[0];$('#pageSubtitle').textContent=meta[1];
    const v=$('#view'), t=document.getElementById(name+'Tpl');
    if(!t){v.innerHTML='<div class="card"><h3>Section unavailable</h3><p class="muted">Please reload the latest app version.</p></div>';return}
    v.innerHTML='';v.appendChild(t.content.cloneNode(true));
    const renderers={dashboard:renderDashboard,myday:renderMyDay,tasks:renderTasks,board:renderBoard,study:renderStudy,wellness:renderWellness,travel:renderTravel,review:renderReview,ai:renderAI,summary:renderSummary,files:renderFiles,backup:renderBackup,settings:renderSettings};
    if(renderers[name]) renderers[name]();
  }catch(err){
    console.error('View error',name,err);
    const v=$('#view');if(v)v.innerHTML='<div class="card error-card"><h3>This section could not open.</h3><p class="muted">Please use Backup regularly and reload the latest version. Technical detail: '+esc(err.message||err)+'</p></div>';
  }
}
function openQuickAdd(defaultCategory='Other'){const m=$('#modal');m.classList.add('open');fillOptions($('#q_category'),CATEGORIES);fillOptions($('#q_priority'),PRIORITIES);fillOptions($('#q_horizon'),HORIZONS);fillOptions($('#q_status'),STATUSES);$('#q_category').value=CATEGORIES.includes(defaultCategory)?defaultCategory:'Other';$('#q_priority').value='Yellow';$('#q_horizon').value='Today';$('#q_status').value='Idea / Capture';$('#q_title').focus()}
function closeQuick(){$('#modal').classList.remove('open');['#q_title','#q_notes','#q_reminder','#q_minutes','#q_next'].forEach(s=>$(s).value='')}
function saveQuick(){const title=$('#q_title').value.trim();if(!title){alert('Please write the task / idea.');return}db.tasks.push({id:uid(),title,category:$('#q_category').value,project:'',priority:$('#q_priority').value,status:$('#q_status').value,horizon:$('#q_horizon').value,startDate:'',dueDate:'',reminderDate:$('#q_reminder').value,owner:'Self',context:'',notes:$('#q_notes').value,tags:'',estimatedMinutes:+($('#q_minutes').value||0),nextAction:$('#q_next').value,waitingFor:'',waitingContact:'',repeat:'None',focus:false,progress:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});save();closeQuick();alert('Saved to SAO Workplace.');if($('#pageTitle')?.textContent==='Dashboard')renderDashboard()}
function dueAttention(t){if(isDone(t))return false;return t.priority==='Red'||t.horizon==='Today'||t.status==='Start Today'||t.status==='Started Today'||(t.reminderDate&&t.reminderDate<=today())||(t.dueDate&&t.dueDate<today())}
function taskMini(t){return `<div class="task-card p-${t.priority.toLowerCase()}"><div class="task-head"><div><div class="task-title">${esc(t.title)}</div><div class="chips"><span class="chip ${t.priority.toLowerCase()}">${esc(t.priority)}</span><span class="chip">${esc(t.category)}</span><span class="chip blue">${esc(t.horizon)}</span></div></div><span class="chip">${esc(t.status)}</span></div></div>`}
function drawPriorityChart(c,tasks){const ctx=c.getContext('2d'),W=c.width,H=c.height;ctx.clearRect(0,0,W,H);const vals=PRIORITIES.map(p=>tasks.filter(t=>t.priority===p.value).length),cols=['#c44f4f','#d78234','#d8ad38','#32805a'],max=Math.max(1,...vals);vals.forEach((v,i)=>{const x=90+i*190,bw=90,h=v/max*(H-100);ctx.fillStyle=cols[i];ctx.fillRect(x,H-50-h,bw,h);ctx.fillStyle='#364456';ctx.font='16px sans-serif';ctx.fillText(PRIORITIES[i].value,x,H-20);ctx.fillText(String(v),x+36,H-60-h)})}

function workspaceTasks(key){const w=WORKSPACES[key];return db.tasks.filter(t=>w.categories.includes(t.category))}
function renderMainWorkspaceButtons(){
  const el=$('#mainWorkspaceButtons');if(!el)return;
  el.innerHTML=Object.entries(WORKSPACES).map(([key,w])=>{
    const all=workspaceTasks(key),open=all.filter(t=>!isDone(t)),attention=open.filter(dueAttention),done=all.filter(isDone).length;
    return `<button class="workspace-launch ${w.color}" onclick="app.openWorkspace('${key}')">
      <span class="workspace-icon">${w.icon}</span><span class="workspace-label">${esc(w.label)}</span>
      <span class="workspace-stats"><b>${open.length}</b> open • <b>${attention.length}</b> attention • ${done} done</span>
    </button>`;
  }).join('');
}
function openWorkspace(key){
  const w=WORKSPACES[key];if(!w)return;
  $$('#nav button').forEach(b=>b.classList.remove('active'));
  $('#pageTitle').textContent=w.label+' Workspace';$('#pageSubtitle').textContent=w.subtitle;
  const v=$('#view'),t=document.getElementById('workspaceTpl');v.innerHTML='';v.appendChild(t.content.cloneNode(true));
  const all=workspaceTasks(key),open=all.filter(t=>!isDone(t)),attention=open.filter(dueAttention).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)),done=all.filter(isDone),todayItems=open.filter(t=>t.horizon==='Today'||t.dueDate===today()||t.reminderDate===today());
  $('#workspaceHero').innerHTML=`<div><span class="workspace-big-icon">${w.icon}</span><span class="eyebrow">FOCUSED WORKSPACE</span><h2>${esc(w.label)}</h2><p>${esc(w.subtitle)}</p><div class="actionrow"><button onclick="app.openQuickAdd('${esc(w.quickCategory)}')">+ Quick Add to ${esc(w.label)}</button><button class="ghost" onclick="app.showView('tasks')">Open All Tasks</button></div></div>`;
  $('#workspaceKpis').innerHTML=[['Open',open.length],['Needs Attention',attention.length],['Today',todayItems.length],['Red Priority',open.filter(t=>t.priority==='Red').length],['Waiting',open.filter(t=>['Waiting','Need Help to Run'].includes(t.status)).length],['Done',done.length]].map(x=>`<div class="kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');
  $('#workspaceAttention').innerHTML=attention.slice(0,10).map(workspaceTaskRow).join('')||'<p class="muted">Nothing urgent in this workspace.</p>';
  const upcoming=open.filter(t=>!attention.includes(t)).sort((a,b)=>horizonRank(a.horizon)-horizonRank(b.horizon)).slice(0,10);
  $('#workspaceUpcoming').innerHTML=upcoming.map(workspaceTaskRow).join('')||'<p class="muted">No upcoming item yet.</p>';
  $('#workspaceTasks').innerHTML=open.sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||horizonRank(a.horizon)-horizonRank(b.horizon)).map(workspaceTaskRow).join('')||'<p class="muted">No open task in this workspace. Use + Add Here.</p>';
  $('#workspaceQuickAdd').onclick=()=>openQuickAdd(w.quickCategory);
  if(key==='study'){
    $('#workspaceExtra').innerHTML=`<div class="card"><div class="cardhead"><div><h3>Study Topics</h3><p class="muted">Study Planner records are shown here too.</p></div><button class="ghost" onclick="app.showView('study')">Open Full Study Planner</button></div>${db.study.filter(s=>s.status!=='Done').map(s=>`<div class="timeline-item"><b>${esc(s.topic)}</b><span>${esc(s.sourceType)} • ${fmt(s.targetDate)} • ${esc(s.status)}</span></div>`).join('')||'<p class="muted">No study topic yet.</p>'}</div>`;
  }
}
function workspaceTaskRow(t){return `<div class="workspace-task-row"><div><b>${esc(t.title)}</b><span>${esc(t.category)} • ${esc(t.priority)} • ${esc(t.status)} • ${esc(t.horizon)}</span>${t.nextAction?`<small>Next: ${esc(t.nextAction)}</small>`:''}</div><div class="actionrow"><button class="ghost" onclick="app.editTask('${t.id}')">Edit</button><button class="ghost" onclick="app.markDone('${t.id}')">Done</button></div></div>`}
function showWorkspaceTasks(key){const w=WORKSPACES[key];showView('tasks');setTimeout(()=>{const f=$('#taskCategoryFilter');if(f&&w.categories.length===1){f.value=w.categories[0];drawTasks()}else if($('#taskSearch')){$('#taskSearch').value=w.categories.join(' ');drawTasks()}},10)}

function renderDashboard(){renderMainWorkspaceButtons();const open=db.tasks.filter(t=>!isDone(t)),attention=open.filter(dueAttention),overdue=open.filter(t=>t.dueDate&&t.dueDate<today()),dueToday=open.filter(t=>t.dueDate===today()||t.reminderDate===today()||t.horizon==='Today'),completed=db.tasks.filter(isDone).length,focus=open.filter(t=>t.focus).length,total=db.tasks.length||1;const focusScore=Math.max(0,Math.min(100,Math.round((completed/total)*45+Math.max(0,40-overdue.length*5)+Math.min(15,focus*5))));const hour=new Date().getHours(),greet=hour<12?'Good Morning':hour<17?'Good Afternoon':'Good Evening';$('#futureGreeting').textContent=`${greet}, ${db.settings.ownerName||'Dr Rajesh Sao'}`;$('#dashKpis').innerHTML=[['Total Tasks',db.tasks.length,'neutral'],['In Progress',open.filter(t=>['Work Started','Started Today'].includes(t.status)).length,'blue'],['Today',dueToday.length,'cyan'],['Overdue',overdue.length,'red'],['Completed',completed,'green'],['Focus Score',focusScore+'%','violet']].map(x=>`<div class="future-kpi ${x[2]}"><span>${x[0]}</span><b>${x[1]}</b><small>${x[0]==='Overdue'?'Needs attention':x[0]==='Focus Score'?'Adaptive score':'Live planner data'}</small></div>`).join('');$('#todayList').innerHTML=attention.sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)).slice(0,7).map(t=>`<div class="future-action-row"><span class="priority-dot ${t.priority.toLowerCase()}"></span><div><b>${esc(t.title)}</b><small>${esc(t.category)} • ${esc(t.status)}</small></div><span class="future-chip">${esc(t.priority)}</span></div>`).join('')||'<p class="muted">No urgent action right now.</p>';$('#horizonBoard').innerHTML=HORIZONS.slice(0,6).map(h=>{const n=open.filter(t=>t.horizon===h).length;return `<div class="future-horizon"><span>${esc(h)}</span><b>${n}</b><i style="--w:${Math.min(100,n*14)}%"></i></div>`}).join('');drawPriorityChart($('#priorityChart'),open);$('#areaOverview').innerHTML=`<div class="future-area-grid">${CATEGORIES.map(c=>{const n=open.filter(t=>t.category===c).length;return n?`<div><b>${n}</b><span>${esc(c)}</span></div>`:''}).join('')}</div>`;$('#studyQueue').innerHTML=db.study.filter(x=>x.status!=='Done').slice(0,5).map(s=>`<div class="future-list-row"><div><b>${esc(s.topic)}</b><span>${esc(s.sourceType)} • ${esc(s.status)}</span></div><small>${s.targetDate?fmt(s.targetDate):'No date'}</small></div>`).join('')||'<p class="muted">No study topic planned.</p>';const w=db.wellness.find(x=>x.date===today());$('#wellnessToday').innerHTML=w?`<div class="future-wellness-grid"><div><b>${w.japa||0}</b><span>Naam Japa</span></div><div><b>${w.exercise||0}m</b><span>Exercise</span></div><div><b>${w.sleep||0}h</b><span>Sleep</span></div><div><b>${w.water||0}L</b><span>Water</span></div></div>`:'<p class="muted">No wellness log today.</p>';$('#aiDashboardInsight').innerHTML=buildDashboardInsight(open,overdue);checkReminders()}
function buildDashboardInsight(open,overdue){const red=open.filter(t=>t.priority==='Red'),waiting=open.filter(t=>['Waiting','Need Help to Run'].includes(t.status)),study=open.filter(t=>['Student / Study','Research'].includes(t.category)),msg=[];if(red.length)msg.push(`<li><b>${red.length} critical item${red.length>1?'s':''}</b> should be reviewed first.</li>`);if(overdue.length)msg.push(`<li><b>${overdue.length} overdue</b> — reschedule, delegate or close them.</li>`);if(waiting.length)msg.push(`<li><b>${waiting.length} blocked/waiting</b> items may need one call or message.</li>`);if(study.length)msg.push(`<li><b>${study.length} study/research tasks</b> are active; protect focus time.</li>`);if(!msg.length)msg.push('<li>Your workload is currently balanced. Keep Today intentionally small.</li>');return `<ul class="ai-insight-list">${msg.slice(0,4).join('')}</ul>`}

function renderMyDay(){
  const open=db.tasks.filter(t=>!isDone(t));
  const focus=open.filter(t=>t.focus).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority));
  const agenda=open.filter(t=>t.horizon==='Today'||t.status==='Start Today'||t.status==='Started Today'||t.dueDate===today()||t.reminderDate===today()).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority));
  const overdue=open.filter(t=>t.dueDate&&t.dueDate<today()).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate)));
  const waiting=open.filter(t=>['Waiting','Need Help to Run','Need More Suggestion'].includes(t.status)||t.waitingFor);
  const minutes=agenda.reduce((s,t)=>s+(+t.estimatedMinutes||0),0);
  $('#myDayMinutes').textContent=minutes;
  $('#myDayKpis').innerHTML=[['Focus',focus.length],['Today',agenda.length],['Overdue',overdue.length],['Waiting',waiting.length],['Est. Hours',(minutes/60).toFixed(1)],['Done Today',db.tasks.filter(t=>t.status==='Done'&&(t.updatedAt||'').slice(0,10)===today()).length]].map(x=>`<div class="kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');
  const mini=a=>a.map(t=>`<div class="task-card p-${t.priority.toLowerCase()}"><div class="task-head"><div><div class="task-title">${esc(t.title)}</div><div class="chips"><span class="chip ${t.priority.toLowerCase()}">${esc(t.priority)}</span><span class="chip">${esc(t.status)}</span></div></div><div class="actionrow"><button onclick="app.editTask('${t.id}')">Open</button><button class="ghost" onclick="app.markDone('${t.id}')">Done</button></div></div>${t.nextAction?`<p class="muted"><b>Next:</b> ${esc(t.nextAction)}</p>`:''}</div>`).join('');
  $('#focusList').innerHTML=mini(focus)||'<p class="muted">No Top Focus task. Edit a task and mark it as Top Focus.</p>';
  $('#agendaList').innerHTML=mini(agenda)||'<p class="muted">Nothing specifically planned for today.</p>';
  $('#rescueList').innerHTML=mini(overdue)||'<p class="muted">No overdue task.</p>';
  $('#waitingList').innerHTML=mini(waiting)||'<p class="muted">Nothing waiting for help or response.</p>';
}
function renderBoard(){
  fillOptions($('#boardArea'),CATEGORIES,true,'All Areas');$('#boardArea').onchange=drawBoard;drawBoard();
}
function drawBoard(){
  const area=$('#boardArea')?.value||'';
  const arr=db.tasks.filter(t=>!area||t.category===area);
  const cols=[
    ['Ideas',t=>['Idea / Capture','Will Start Soon'].includes(t.status)],
    ['Ready',t=>['Start Today','Pending'].includes(t.status)],
    ['Doing',t=>['Started Today','Work Started','Need Modification'].includes(t.status)],
    ['Waiting',t=>['Waiting','Need More Suggestion','Need Help to Run'].includes(t.status)],
    ['Done',t=>t.status==='Done'],
    ['Stopped',t=>['Need to Stop','Stopped'].includes(t.status)]
  ];
  $('#kanbanBoard').innerHTML=cols.map(([name,fn])=>`<div class="kanban-col"><div class="kanban-head"><b>${name}</b><span>${arr.filter(fn).length}</span></div>${arr.filter(fn).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)).map(t=>`<div class="kanban-task p-${t.priority.toLowerCase()}"><b>${esc(t.title)}</b><span>${esc(t.category)}</span><button class="ghost" onclick="app.editTask('${t.id}')">Open</button></div>`).join('')||'<p class="muted tiny">Empty</p>'}</div>`).join('');
}
function renderReview(){
  $('#reviewRefresh').onclick=renderReview;
  const open=db.tasks.filter(t=>!isDone(t));
  const overdue=open.filter(t=>t.dueDate&&t.dueDate<today());
  const stale=open.filter(t=>{const d=(t.updatedAt||t.createdAt||'').slice(0,10);if(!d)return false;return (new Date(today())-new Date(d))/86400000>=14});
  const waiting=open.filter(t=>['Waiting','Need Help to Run','Need More Suggestion'].includes(t.status)||t.waitingFor);
  const long=open.filter(t=>['3 Months Later','6 Months Later','1 Year Later','Someday / No Date'].includes(t.horizon));
  $('#reviewKpis').innerHTML=[['Overdue',overdue.length],['Stale 14+ days',stale.length],['Waiting / Help',waiting.length],['Long-term',long.length],['Open',open.length],['Done',db.tasks.filter(isDone).length]].map(x=>`<div class="kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');
  const list=a=>a.map(t=>`<div class="task-card p-${t.priority.toLowerCase()}"><div class="task-head"><div class="task-title">${esc(t.title)}</div><button onclick="app.editTask('${t.id}')">Review</button></div><div class="chips"><span class="chip ${t.priority.toLowerCase()}">${esc(t.priority)}</span><span class="chip">${esc(t.status)}</span><span class="chip blue">${esc(t.horizon)}</span></div><div class="actionrow"><button class="ghost" onclick="app.reschedule('${t.id}','Tomorrow')">Tomorrow</button><button class="ghost" onclick="app.reschedule('${t.id}','1 Week Later')">Next Week</button></div></div>`).join('')||'<p class="muted">None.</p>';
  $('#reviewOverdue').innerHTML=list(overdue);$('#reviewStale').innerHTML=list(stale);$('#reviewWaiting').innerHTML=list(waiting);$('#reviewLong').innerHTML=list(long);
  $('#reflectionHistory').innerHTML=db.reflections.slice().reverse().slice(0,6).map(r=>`<div class="timeline-item"><b>${fmt(r.date)}</b><span><b>Went well:</b> ${esc(r.good||'-')}<br><b>Stuck:</b> ${esc(r.stuck||'-')}<br><b>Next:</b> ${esc(r.next||'-')}</span></div>`).join('')||'<p class="muted">No reflection saved yet.</p>';
  $('#saveReflection').onclick=()=>{db.reflections.push({id:uid(),date:today(),good:$('#rv_good').value,stuck:$('#rv_stuck').value,next:$('#rv_next').value});save();alert('Weekly reflection saved.');renderReview()};
}
function reschedule(id,horizon){const t=db.tasks.find(x=>x.id===id);if(!t)return;t.horizon=horizon;t.updatedAt=new Date().toISOString();if(horizon==='Tomorrow'){const d=new Date();d.setDate(d.getDate()+1);t.startDate=d.toISOString().slice(0,10)}save();if($('#pageTitle')?.textContent==='Review Center')renderReview();else if($('#pageTitle')?.textContent==='Tasks & Projects')drawTasks()}

function renderTasks(){fillOptions($('#taskCategoryFilter'),CATEGORIES,true,'All Areas');fillOptions($('#taskPriorityFilter'),PRIORITIES,true,'All Priority');fillOptions($('#taskStatusFilter'),STATUSES,true,'All Status');fillOptions($('#taskHorizonFilter'),HORIZONS,true,'All Start Horizons');$('#newTaskBtn').onclick=()=>editTask();['#taskSearch','#taskCategoryFilter','#taskPriorityFilter','#taskStatusFilter','#taskHorizonFilter'].forEach(s=>$(s).oninput=drawTasks);drawTasks()}
function editTask(id=''){const t=id?db.tasks.find(x=>x.id===id):{};$('#taskEditor').innerHTML=`<div class="card"><div class="cardhead"><div><span class="eyebrow">TASK / PROJECT DETAILS</span><h3>${t.id?'Edit':'New'} Task or Project</h3></div><button class="ghost" id="closeTaskEditor">Close</button></div><div class="formgrid"><label>Title *<input id="t_title" value="${esc(t.title||'')}"></label><label>Area<select id="t_category"></select></label><label>Project / Subject<input id="t_project" value="${esc(t.project||'')}"></label><label>Priority<select id="t_priority"></select></label><label>Status<select id="t_status"></select></label><label>When to Start<select id="t_horizon"></select></label><label>Start Date<input id="t_start" type="date" value="${t.startDate||''}"></label><label>Due Date<input id="t_due" type="date" value="${t.dueDate||''}"></label><label>Reminder Date<input id="t_reminder" type="date" value="${t.reminderDate||''}"></label><label>Responsible / With Whom<input id="t_owner" value="${esc(t.owner||'Self')}"></label><label>Context / Place<input id="t_context" value="${esc(t.context||'')}"></label><label>Tags<input id="t_tags" value="${esc(t.tags||'')}"></label></div><label>Notes / Why / Strategy / Help Needed<textarea id="t_notes">${esc(t.notes||'')}</textarea></label><div class="actionrow"><button id="saveTaskBtn">Save Task / Project</button></div></div>`;fillOptions($('#t_category'),CATEGORIES);fillOptions($('#t_priority'),PRIORITIES);fillOptions($('#t_status'),STATUSES);fillOptions($('#t_horizon'),HORIZONS);$('#t_category').value=t.category||'Other';$('#t_priority').value=t.priority||'Yellow';$('#t_status').value=t.status||'Idea / Capture';$('#t_horizon').value=t.horizon||'Today';$('#t_repeat').value=t.repeat||'None';$('#t_focus').value=String(!!t.focus);$('#closeTaskEditor').onclick=()=>$('#taskEditor').innerHTML='';$('#saveTaskBtn').onclick=()=>saveTask(id);$('#taskEditor').scrollIntoView({behavior:'smooth'})}
function saveTask(id){const title=$('#t_title').value.trim();if(!title){alert('Title required.');return}const x={id:id||uid(),title,category:$('#t_category').value,project:$('#t_project').value,priority:$('#t_priority').value,status:$('#t_status').value,horizon:$('#t_horizon').value,startDate:$('#t_start').value,dueDate:$('#t_due').value,reminderDate:$('#t_reminder').value,owner:$('#t_owner').value,context:$('#t_context').value,tags:$('#t_tags').value,nextAction:$('#t_next').value,estimatedMinutes:+$('#t_minutes').value||0,progress:Math.max(0,Math.min(100,+$('#t_progress').value||0)),waitingFor:$('#t_waiting').value,waitingContact:$('#t_waitcontact').value,repeat:$('#t_repeat').value,focus:$('#t_focus').value==='true',notes:$('#t_notes').value,createdAt:id?(db.tasks.find(t=>t.id===id)?.createdAt||new Date().toISOString()):new Date().toISOString(),updatedAt:new Date().toISOString()};if(id)db.tasks=db.tasks.map(t=>t.id===id?x:t);else db.tasks.push(x);save();$('#taskEditor').innerHTML='';drawTasks();alert('Saved.')}
function drawTasks(){const q=($('#taskSearch')?.value||'').toLowerCase(),cat=$('#taskCategoryFilter')?.value||'',pri=$('#taskPriorityFilter')?.value||'',st=$('#taskStatusFilter')?.value||'',hor=$('#taskHorizonFilter')?.value||'';const arr=db.tasks.filter(t=>[t.title,t.category,t.project,t.owner,t.context,t.tags,t.notes].join(' ').toLowerCase().includes(q)).filter(t=>!cat||t.category===cat).filter(t=>!pri||t.priority===pri).filter(t=>!st||t.status===st).filter(t=>!hor||t.horizon===hor).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||horizonRank(a.horizon)-horizonRank(b.horizon));const open=arr.filter(t=>!isDone(t));$('#taskKpis').innerHTML=[['Shown',arr.length],['Open',open.length],['Red',open.filter(t=>t.priority==='Red').length],['Pending',open.filter(t=>t.status==='Pending').length],['Done',arr.filter(isDone).length]].map(x=>`<div class="kpi"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');$('#tasksList').innerHTML=arr.map(t=>`<div class="task-card p-${t.priority.toLowerCase()}"><div class="task-head"><div><div class="task-title">${esc(t.title)}</div><div class="chips"><span class="chip ${t.priority.toLowerCase()}">${esc(t.priority)}</span><span class="chip">${esc(t.category)}</span>${t.project?`<span class="chip blue">${esc(t.project)}</span>`:''}<span class="chip">${esc(t.status)}</span></div></div><div class="actionrow"><button onclick="app.editTask('${t.id}')">Edit</button><button class="ghost" onclick="app.markDone('${t.id}')">Done</button><button class="ghost" onclick="app.shareTask('${t.id}')">Share</button><button class="ghost" onclick="app.deleteTask('${t.id}')">Delete</button></div></div><div class="task-meta"><div>Start Horizon<b>${esc(t.horizon)}</b></div><div>Due<b>${fmt(t.dueDate)}</b></div><div>Reminder<b>${fmt(t.reminderDate)}</b></div><div>Responsibility<b>${esc(t.owner||'-')}</b></div></div>${t.notes?`<p class="muted">${esc(t.notes)}</p>`:''}</div>`).join('')||'<p class="muted">No matching task.</p>'}
function addDaysISO(d,n){const x=new Date((d||today())+'T00:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function addMonthsISO(d,n){const x=new Date((d||today())+'T00:00:00');x.setMonth(x.getMonth()+n);return x.toISOString().slice(0,10)}
function markDone(id){const t=db.tasks.find(x=>x.id===id);if(!t)return;t.status='Done';t.progress=100;t.updatedAt=new Date().toISOString();if(t.repeat&&t.repeat!=='None'){const next={...t,id:uid(),status:'Pending',progress:0,focus:false,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};const base=t.dueDate||t.startDate||today();if(t.repeat==='Daily')next.dueDate=addDaysISO(base,1);if(t.repeat==='Weekly')next.dueDate=addDaysISO(base,7);if(t.repeat==='Monthly')next.dueDate=addMonthsISO(base,1);if(t.repeat==='Yearly')next.dueDate=addMonthsISO(base,12);next.startDate=next.dueDate;next.reminderDate=next.dueDate;db.tasks.push(next)}save();if($('#tasksList'))drawTasks();}function deleteTask(id){if(confirm('Delete this task?')){db.tasks=db.tasks.filter(x=>x.id!==id);save();drawTasks()}}async function shareTask(id){const t=db.tasks.find(x=>x.id===id);if(!t)return;const text=`${t.title}\nArea: ${t.category}\nPriority: ${t.priority}\nStatus: ${t.status}\nStart: ${t.horizon}\nDue: ${fmt(t.dueDate)}\nNotes: ${t.notes||'-'}`;if(navigator.share)await navigator.share({title:'SAO Workplace Task',text});else{await navigator.clipboard.writeText(text);alert('Copied.')}}
function renderStudy(){fillOptions($('#studyStatusFilter'),STATUSES,true,'All Status');$('#studyStatusFilter').onchange=drawStudy;$('#newStudyBtn').onclick=()=>editStudy();drawStudy()}
function editStudy(id=''){const s=id?db.study.find(x=>x.id===id):{};$('#studyEditor').innerHTML=`<div class="formgrid"><label>Topic *<input id="s_topic" value="${esc(s.topic||'')}"></label><label>Subject / Domain<input id="s_subject" value="${esc(s.subject||'')}"></label><label>Source Type<select id="s_source"></select></label><label>Source / Link / Person<input id="s_detail" value="${esc(s.sourceDetail||'')}"></label><label>Target Date<input id="s_target" type="date" value="${s.targetDate||''}"></label><label>Planned Hours<input id="s_hours" type="number" step=".5" value="${s.hours||''}"></label><label>Status<select id="s_status"></select></label><label>Priority<select id="s_priority"></select></label></div><label>Study Strategy / Notes<textarea id="s_notes">${esc(s.notes||'')}</textarea></label><div class="actionrow"><button id="saveStudy">Save Study Topic</button><button class="ghost" id="closeStudy">Cancel</button></div>`;fillOptions($('#s_source'),SOURCE_TYPES);fillOptions($('#s_status'),STATUSES);fillOptions($('#s_priority'),PRIORITIES);$('#s_source').value=s.sourceType||'Book';$('#s_status').value=s.status||'Will Start Soon';$('#s_priority').value=s.priority||'Yellow';$('#saveStudy').onclick=()=>{const topic=$('#s_topic').value.trim();if(!topic){alert('Topic required.');return}const x={id:id||uid(),topic,subject:$('#s_subject').value,sourceType:$('#s_source').value,sourceDetail:$('#s_detail').value,targetDate:$('#s_target').value,hours:+$('#s_hours').value||0,status:$('#s_status').value,priority:$('#s_priority').value,notes:$('#s_notes').value};if(id)db.study=db.study.map(y=>y.id===id?x:y);else db.study.push(x);save();$('#studyEditor').innerHTML='';drawStudy()};$('#closeStudy').onclick=()=>$('#studyEditor').innerHTML=''}
function drawStudy(){const st=$('#studyStatusFilter')?.value||'',arr=db.study.filter(x=>!st||x.status===st).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||(a.targetDate||'9999').localeCompare(b.targetDate||'9999'));$('#studyList').innerHTML=arr.map(s=>`<div class="task-card p-${s.priority.toLowerCase()}"><div class="task-head"><div><div class="task-title">${esc(s.topic)}</div><div class="chips"><span class="chip ${s.priority.toLowerCase()}">${esc(s.priority)}</span><span class="chip">${esc(s.sourceType)}</span><span class="chip">${esc(s.status)}</span></div></div><button onclick="app.editStudy('${s.id}')">Edit</button></div><div class="task-meta"><div>Subject<b>${esc(s.subject||'-')}</b></div><div>Target<b>${fmt(s.targetDate)}</b></div><div>Hours<b>${s.hours||0}</b></div><div>Source<b>${esc(s.sourceDetail||'-')}</b></div></div></div>`).join('')||'<p class="muted">No study topic.</p>'}
function renderWellness(){$('#wellnessDate').value=today();$('#wellnessDate').onchange=drawWellnessForm;drawWellnessForm()}
function drawWellnessForm(){const d=$('#wellnessDate').value||today(),w=db.wellness.find(x=>x.date===d)||{};$('#wellnessForm').innerHTML=`<div class="wellness-grid"><div class="wellbox"><h4>Radha Naam Japa</h4><label>Count<input id="w_japa" type="number" value="${w.japa||0}"></label><label>Mala<input id="w_mala" type="number" value="${w.mala||0}"></label></div><div class="wellbox"><h4>Sadhana / Pooja</h4><label>Minutes<input id="w_sadhana" type="number" value="${w.sadhana||0}"></label><label>Vrata / Ekadashi<select id="w_vrata"><option>No</option><option ${w.vrata==='Yes'?'selected':''}>Yes</option></select></label></div><div class="wellbox"><h4>Body Health</h4><label>Exercise min<input id="w_exercise" type="number" value="${w.exercise||0}"></label><label>Yoga min<input id="w_yoga" type="number" value="${w.yoga||0}"></label></div><div class="wellbox"><h4>Recovery</h4><label>Sleep hours<input id="w_sleep" type="number" step=".5" value="${w.sleep||0}"></label><label>Diet adherence %<input id="w_diet" type="number" min="0" max="100" value="${w.diet||0}"></label></div><div class="wellbox"><h4>Dana / Donation</h4><label>Amount ₹<input id="w_donation" type="number" value="${w.donation||0}"></label><label>Where / Purpose<input id="w_donationNote" value="${esc(w.donationNote||'')}"></label></div><div class="wellbox"><h4>Steps / Walk</h4><label>Steps<input id="w_steps" type="number" value="${w.steps||0}"></label><label>Water (L)<input id="w_water" type="number" step=".1" value="${w.water||0}"></label></div><div class="wellbox"><h4>Temple / Darshan</h4><label>Darshan / Yatra<input id="w_darshan" value="${esc(w.darshan||'')}"></label></div><div class="wellbox"><h4>Reflection</h4><label>Notes<textarea id="w_notes">${esc(w.notes||'')}</textarea></label></div></div><div class="actionrow"><button id="saveWellness">Save Daily Log</button></div>`;$('#saveWellness').onclick=()=>saveWellness(d);renderWellnessTotals();renderWellnessHistory()}
function saveWellness(date){const x={date,japa:+$('#w_japa').value||0,mala:+$('#w_mala').value||0,sadhana:+$('#w_sadhana').value||0,vrata:$('#w_vrata').value,exercise:+$('#w_exercise').value||0,yoga:+$('#w_yoga').value||0,sleep:+$('#w_sleep').value||0,diet:+$('#w_diet').value||0,donation:+$('#w_donation').value||0,donationNote:$('#w_donationNote').value,steps:+$('#w_steps').value||0,water:+$('#w_water').value||0,darshan:$('#w_darshan').value,notes:$('#w_notes').value};const i=db.wellness.findIndex(y=>y.date===date);if(i>=0)db.wellness[i]=x;else db.wellness.push(x);save();renderWellnessTotals();renderWellnessHistory();alert('Daily wellness / sadhana log saved.')}
function renderWellnessTotals(){const month=($('#wellnessDate').value||today()).slice(0,7),a=db.wellness.filter(x=>x.date.startsWith(month));const sum=k=>a.reduce((s,x)=>s+(+x[k]||0),0),avg=k=>a.length?(sum(k)/a.length).toFixed(1):0;$('#wellnessTotals').innerHTML=`<div class="metric-grid"><div class="metric"><b>${sum('japa').toLocaleString()}</b><span>Total Naam Japa</span></div><div class="metric"><b>${sum('mala')}</b><span>Total Mala</span></div><div class="metric"><b>${a.filter(x=>x.vrata==='Yes').length}</b><span>Vrata / Ekadashi</span></div><div class="metric"><b>₹${sum('donation').toLocaleString()}</b><span>Dana</span></div><div class="metric"><b>${sum('exercise')}</b><span>Exercise min</span></div><div class="metric"><b>${avg('sleep')}</b><span>Avg Sleep h</span></div><div class="metric"><b>${sum('steps').toLocaleString()}</b><span>Steps</span></div><div class="metric"><b>${a.length}</b><span>Days Logged</span></div></div>`}
function renderWellnessHistory(){$('#wellnessHistory').innerHTML=db.wellness.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10).map(w=>`<div class="timeline-item"><b>${fmt(w.date)}</b><span>Japa ${w.japa||0} • Mala ${w.mala||0} • Exercise ${w.exercise||0} min • Sleep ${w.sleep||0}h ${w.vrata==='Yes'?'• Vrata':''}</span></div>`).join('')||'<p class="muted">No log yet.</p>'}
function renderTravel(){fillOptions($('#travelStatusFilter'),TRAVEL_STATUSES,true,'All Status');$('#travelStatusFilter').onchange=drawTravel;$('#newTravelBtn').onclick=()=>editTravel();drawTravel()}
function editTravel(id=''){const t=id?db.travel.find(x=>x.id===id):{};$('#travelEditor').innerHTML=`<div class="formgrid"><label>Event / Destination *<input id="tr_title" value="${esc(t.title||'')}"></label><label>Purpose<input id="tr_purpose" value="${esc(t.purpose||'')}"></label><label>Place / City<input id="tr_place" value="${esc(t.place||'')}"></label><label>Start Date<input id="tr_start" type="date" value="${t.startDate||''}"></label><label>Return Date<input id="tr_return" type="date" value="${t.returnDate||''}"></label><label>Status<select id="tr_status"></select></label><label>Travel Mode<select id="tr_mode"><option>Train</option><option>Flight</option><option>Bus</option><option>Car</option><option>Bike</option><option>Mixed</option></select></label><label>Ticket Status<input id="tr_ticket" value="${esc(t.ticketStatus||'')}"></label><label>With Whom<input id="tr_with" value="${esc(t.withWhom||'')}"></label><label>Estimated Cost ₹<input id="tr_cost" type="number" value="${t.cost||''}"></label><label>Nearby Places<textarea id="tr_nearby">${esc(t.nearby||'')}</textarea></label><label>Schedule / Timing<textarea id="tr_schedule">${esc(t.schedule||'')}</textarea></label></div><label>Why / Strategy / Notes<textarea id="tr_notes">${esc(t.notes||'')}</textarea></label><div class="actionrow"><button id="saveTravel">Save Travel Plan</button><button class="ghost" id="cancelTravel">Cancel</button></div>`;fillOptions($('#tr_status'),TRAVEL_STATUSES);$('#tr_status').value=t.status||'Idea';$('#tr_mode').value=t.mode||'Train';$('#saveTravel').onclick=()=>{const title=$('#tr_title').value.trim();if(!title){alert('Event / destination required.');return}const x={id:id||uid(),title,purpose:$('#tr_purpose').value,place:$('#tr_place').value,startDate:$('#tr_start').value,returnDate:$('#tr_return').value,status:$('#tr_status').value,mode:$('#tr_mode').value,ticketStatus:$('#tr_ticket').value,withWhom:$('#tr_with').value,cost:+$('#tr_cost').value||0,nearby:$('#tr_nearby').value,schedule:$('#tr_schedule').value,notes:$('#tr_notes').value};if(id)db.travel=db.travel.map(y=>y.id===id?x:y);else db.travel.push(x);save();$('#travelEditor').innerHTML='';drawTravel()};$('#cancelTravel').onclick=()=>$('#travelEditor').innerHTML=''}
function drawTravel(){const st=$('#travelStatusFilter')?.value||'',arr=db.travel.filter(x=>!st||x.status===st).sort((a,b)=>(a.startDate||'9999').localeCompare(b.startDate||'9999'));$('#travelList').innerHTML=arr.map(t=>`<div class="task-card p-${t.status==='Cancelled'?'red':'green'}"><div class="task-head"><div><div class="task-title">${esc(t.title)}</div><div class="chips"><span class="chip blue">${esc(t.status)}</span><span class="chip">${esc(t.mode||'-')}</span></div></div><button onclick="app.editTravel('${t.id}')">Edit</button></div><div class="task-meta"><div>Place<b>${esc(t.place||'-')}</b></div><div>Start<b>${fmt(t.startDate)}</b></div><div>Return<b>${fmt(t.returnDate)}</b></div><div>Cost<b>₹${(t.cost||0).toLocaleString()}</b></div></div><p class="muted"><b>Tickets:</b> ${esc(t.ticketStatus||'-')} • <b>With:</b> ${esc(t.withWhom||'-')}</p>${t.nearby?`<p class="muted"><b>Nearby:</b> ${esc(t.nearby)}</p>`:''}</div>`).join('')||'<p class="muted">No travel or seminar plan.</p>'}

let interpretedTask=null;
function localInterpretCommand(text){
  const raw=(text||'').trim(), s=raw.toLowerCase();
  if(!raw)return null;
  let category='Other';
  if(/clinic|patient|doctor|opd|hospital/.test(s))category='Clinic Management';
  else if(/study|read|book|article|research|thesis|learn/.test(s))category=/research|thesis/.test(s)?'Research':'Student / Study';
  else if(/home|family|house|ghar/.test(s))category='Home';
  else if(/app|github|code|website|ai|software/.test(s))category='App Development & AI';
  else if(/bank|insurance|policy|loan/.test(s))category='Banking & Insurance';
  else if(/yoga|exercise|sleep|diet|health/.test(s))category='Health & Fitness';
  else if(/pooja|puja|japa|mala|sadhana|vrata|ekadashi|temple/.test(s))category='Spiritual / Sadhana';
  else if(/travel|seminar|flight|train|tour|darshan/.test(s))category='Travel / Seminar';

  let priority='Yellow';
  if(/urgent|critical|immediately|asap|red priority|very important/.test(s))priority='Red';
  else if(/high priority|important soon/.test(s))priority='Orange';
  else if(/routine|low priority|whenever/.test(s))priority='Green';

  let horizon='Today';
  if(/tomorrow|kal\b/.test(s))horizon='Tomorrow';
  else if(/next week|one week|1 week/.test(s))horizon='1 Week Later';
  else if(/next month|one month|1 month/.test(s))horizon='1 Month Later';
  else if(/three months|3 months/.test(s))horizon='3 Months Later';
  else if(/six months|6 months/.test(s))horizon='6 Months Later';
  else if(/one year|1 year|next year/.test(s))horizon='1 Year Later';
  else if(/someday|later sometime/.test(s))horizon='Someday / No Date';

  const mm=s.match(/(\d+)\s*(minute|min|minutes|mins)\b/); const hh=s.match(/(\d+(?:\.\d+)?)\s*(hour|hours|hr|hrs)\b/);
  const estimatedMinutes=mm?+mm[1]:(hh?Math.round(+hh[1]*60):0);
  let status='Idea / Capture';
  if(/start today/.test(s))status='Start Today';
  else if(/started today/.test(s))status='Started Today';
  else if(/waiting/.test(s))status='Waiting';
  else if(/pending/.test(s))status='Pending';
  else if(/need help|help me/.test(s))status='Need Help to Run';

  let title=raw.replace(/\b(today|tomorrow|next week|next month|urgent|critical|high priority|low priority|red priority|\d+\s*(minutes?|mins?|hours?|hrs?))\b/gi,' ').replace(/\s+/g,' ').trim();
  title=title.replace(/^(please\s+)?(remind me to|remember to|i need to|need to|please)\s+/i,'').trim();
  if(!title)title=raw;
  return {title,category,priority,horizon,status,estimatedMinutes,nextAction:title,notes:'Captured by SAO Smart Command',reminderDate:'',focus:false};
}
function showCommandPreview(){
  const el=$('#commandPreview'); if(!el)return;
  const t=interpretedTask;
  if(!t){el.innerHTML='<p class="muted">Enter a sentence, then choose Interpret & Preview.</p>';return}
  el.innerHTML=`<div class="preview-grid"><div><span>Task</span><b>${esc(t.title)}</b></div><div><span>Area</span><b>${esc(t.category)}</b></div><div><span>Priority</span><b>${esc(t.priority)}</b></div><div><span>Start</span><b>${esc(t.horizon)}</b></div><div><span>Status</span><b>${esc(t.status)}</b></div><div><span>Estimate</span><b>${t.estimatedMinutes||0} min</b></div></div>`;
}
function saveInterpretedTask(){
  if(!interpretedTask){alert('Please Interpret & Preview first.');return}
  const t=interpretedTask;
  db.tasks.push({id:uid(),project:'',startDate:'',dueDate:'',owner:'Self',context:'',tags:'',waitingFor:'',waitingContact:'',repeat:'None',progress:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),...t});
  save(); alert('Smart task saved to SAO Workplace.'); interpretedTask=null; if($('#aiCommandInput'))$('#aiCommandInput').value=''; showCommandPreview(); renderAI();
}
function startVoiceCapture(targetSelector='#aiCommandInput'){
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
  const state=$('#voiceState');
  if(!SR){if(state)state.textContent='Voice recognition is not supported in this browser. You can still type normally.';alert('Voice recognition is not supported in this browser.');return}
  const r=new SR(); r.lang='en-IN'; r.interimResults=false; r.maxAlternatives=1;
  if(state)state.textContent='Listening… speak your task naturally.';
  r.onresult=e=>{const text=e.results[0][0].transcript;const target=$(targetSelector);if(target)target.value=text;if(state)state.textContent='Voice captured. Review the text, then Interpret & Preview.';interpretedTask=localInterpretCommand(text);showCommandPreview()};
  r.onerror=e=>{if(state)state.textContent='Voice capture could not complete: '+e.error};
  r.start();
}
function buildDailyBrief(){
  const open=db.tasks.filter(t=>!isDone(t));
  const overdue=open.filter(t=>t.dueDate&&t.dueDate<today());
  const attention=open.filter(dueAttention).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||horizonRank(a.horizon)-horizonRank(b.horizon));
  const top=attention.slice(0,3);
  const waiting=open.filter(t=>['Waiting','Need Help to Run','Need More Suggestion'].includes(t.status));
  const study=db.study.filter(s=>s.status!=='Done').length;
  const mins=attention.filter(t=>t.horizon==='Today'||t.dueDate===today()).reduce((s,t)=>s+(+t.estimatedMinutes||0),0);
  let lines=[];
  lines.push(`You have ${open.length} open task${open.length===1?'':'s'}, ${overdue.length} overdue, and ${attention.length} needing attention.`);
  if(top.length)lines.push('Top focus: '+top.map(t=>t.title).join(' • ')+'.');
  if(mins)lines.push(`Estimated planned workload today is about ${mins} minutes.`);
  if(waiting.length)lines.push(`${waiting.length} item${waiting.length===1?' is':'s are'} waiting or need help; follow-up may unlock progress.`);
  if(study)lines.push(`${study} study topic${study===1?' is':'s are'} still open.`);
  if(!open.length)lines.push('Your task list is clear. Use the time for review, recovery or long-term planning.');
  return lines;
}
function speakText(text){
  if(!('speechSynthesis' in window)){alert('Read-aloud is not supported in this browser.');return}
  speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text);u.lang='en-IN';u.rate=.96;speechSynthesis.speak(u);
}
function prepareMyDay(){
  const candidates=db.tasks.filter(t=>!isDone(t)).sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||horizonRank(a.horizon)-horizonRank(b.horizon)).slice(0,3);
  if(!candidates.length){alert('No open tasks to prepare.');return}
  if(!confirm('Mark the top 3 suggested tasks as Focus and Start Today?'))return;
  const ids=new Set(candidates.map(t=>t.id));
  db.tasks=db.tasks.map(t=>ids.has(t.id)?{...t,focus:true,horizon:'Today',status:t.status==='Idea / Capture'?'Start Today':t.status,updatedAt:new Date().toISOString()}:t);save();renderAI();alert('My Day prepared with top 3 focus tasks.');
}
function applyTheme(){document.body.classList.toggle('dark-mode',db.settings.theme==='Dark')}
function renderAI(){
  const open=db.tasks.filter(t=>!isDone(t)),overdue=open.filter(t=>t.dueDate&&t.dueDate<today()),red=open.filter(t=>t.priority==='Red'),waiting=open.filter(t=>['Waiting','Need Help to Run','Need More Suggestion'].includes(t.status)),longTerm=open.filter(t=>['3 Months Later','6 Months Later','1 Year Later','Someday / No Date'].includes(t.horizon)),todayWork=open.filter(t=>t.horizon==='Today'||t.dueDate===today()||t.reminderDate===today()),mins=todayWork.reduce((s,t)=>s+(+t.estimatedMinutes||0),0);
  $('#aiKpis').innerHTML=[['Critical',red.length,'red'],['Overdue',overdue.length,'orange'],['Waiting',waiting.length,'blue'],['Long-term',longTerm.length,'violet'],['Today Load',mins+'m','cyan'],['Open Work',open.length,'green']].map(x=>`<div class="future-kpi ${x[2]}"><span>${x[0]}</span><b>${x[1]}</b><small>Live planner analysis</small></div>`).join('');
  $('#aiAttention').innerHTML=buildDashboardInsight(open,overdue);
  const top=open.slice().sort((a,b)=>priorityRank(a.priority)-priorityRank(b.priority)||horizonRank(a.horizon)-horizonRank(b.horizon)).slice(0,5);
  $('#aiStrategy').innerHTML=`<ol class="ai-strategy-list">${top.map((t,i)=>`<li><b>${i+1}. ${esc(t.title)}</b><span>${esc(t.category)} • ${esc(t.nextAction||'Define the next concrete action')}</span></li>`).join('')||'<li>No open task. Use this time for review or recovery.</li>'}</ol>`;
  const areas=CATEGORIES.map(c=>({c,n:open.filter(t=>t.category===c).length})).filter(x=>x.n).sort((a,b)=>b.n-a.n).slice(0,8);
  $('#aiBalance').innerHTML=`<div class="balance-bars">${areas.map(x=>`<div><span>${esc(x.c)}</span><b>${x.n}</b><i style="--w:${Math.min(100,x.n/Math.max(1,areas[0]?.n||1)*100)}%"></i></div>`).join('')||'<p class="muted">No workload yet.</p>'}</div>`;
  const risks=[];if(overdue.length>=3)risks.push(`${overdue.length} overdue tasks indicate scheduling debt.`);if(waiting.length>=3)risks.push(`${waiting.length} blocked/waiting tasks may need delegation.`);if(longTerm.length>=5)risks.push(`${longTerm.length} long-term items risk becoming forgotten commitments.`);const untouched=open.filter(t=>t.updatedAt&&Math.floor((Date.now()-new Date(t.updatedAt))/86400000)>=14).length;if(untouched)risks.push(`${untouched} open task${untouched>1?'s':''} untouched for 14+ days.`);$('#aiRisks').innerHTML=risks.length?`<ul class="risk-list">${risks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<div class="ai-clear-state">No major planning risk detected from current local data.</div>';
  const brief=buildDailyBrief();$('#smartDailyBrief').innerHTML=`<ul class="smart-brief-list">${brief.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
  $('#interpretCommandBtn').onclick=()=>{interpretedTask=localInterpretCommand($('#aiCommandInput').value);showCommandPreview()};
  $('#saveInterpretedBtn').onclick=saveInterpretedTask;$('#clearCommandBtn').onclick=()=>{$('#aiCommandInput').value='';interpretedTask=null;showCommandPreview()};
  $('#aiVoiceBtn').onclick=()=>startVoiceCapture('#aiCommandInput');$('#prepareDayBtn').onclick=prepareMyDay;$('#speakBriefBtn').onclick=()=>speakText(brief.join(' '));showCommandPreview();
}
function renderSummary(){const open=db.tasks.filter(t=>!isDone(t)),byPri=p=>open.filter(t=>t.priority===p),soon=open.filter(t=>['Today','Tomorrow','2-3 Days','1 Week Later'].includes(t.horizon));$('#masterSummary').innerHTML=`<div class="metric-grid"><div class="metric"><b>${open.length}</b><span>Open Tasks</span></div><div class="metric"><b>${byPri('Red').length}</b><span>Critical Red</span></div><div class="metric"><b>${soon.length}</b><span>Next 7 Days</span></div><div class="metric"><b>${db.study.filter(s=>s.status!=='Done').length}</b><span>Study Pending</span></div></div><div class="summary-section"><h4>Critical / Red Priority</h4>${summaryTasks(byPri('Red'))}</div><div class="summary-section"><h4>Start Today / Tomorrow / This Week</h4>${summaryTasks(soon)}</div><div class="summary-section"><h4>By Area</h4><div class="area-grid">${CATEGORIES.map(c=>{const n=open.filter(t=>t.category===c).length;return n?`<div class="area-box"><b>${n}</b><span>${esc(c)}</span></div>`:''}).join('')}</div></div><div class="summary-section"><h4>Status Snapshot</h4><div class="area-grid">${STATUSES.map(s=>{const n=db.tasks.filter(t=>t.status===s).length;return n?`<div class="area-box"><b>${n}</b><span>${esc(s)}</span></div>`:''}).join('')}</div></div>`;$('#printSummary').onclick=()=>window.print();$('#shareSummary').onclick=shareSummary}
function summaryTasks(a){return a.length?`<table class="summary-table"><thead><tr><th>Task</th><th>Area</th><th>Priority</th><th>Status</th><th>Start</th><th>Due</th></tr></thead><tbody>${a.slice(0,30).map(t=>`<tr><td>${esc(t.title)}</td><td>${esc(t.category)}</td><td>${esc(t.priority)}</td><td>${esc(t.status)}</td><td>${esc(t.horizon)}</td><td>${fmt(t.dueDate)}</td></tr>`).join('')}</tbody></table>`:'<p class="muted">None.</p>'}async function shareSummary(){const text=$('#masterSummary').innerText;if(navigator.share)await navigator.share({title:'SAO Workplace Summary',text});else{await navigator.clipboard.writeText(text);alert('Summary copied.')}}
let fileDB,picked=[];function openFileDB(){return new Promise((res,rej)=>{const r=indexedDB.open(FILE_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>{fileDB=r.result;res()};r.onerror=()=>rej(r.error)})}async function putFile(x){if(!fileDB)await openFileDB();return new Promise((res,rej)=>{const tx=fileDB.transaction('files','readwrite');tx.objectStore('files').put(x);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}async function allFiles(){if(!fileDB)await openFileDB();return new Promise((res,rej)=>{const r=fileDB.transaction('files').objectStore('files').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}async function getFile(id){return (await allFiles()).find(x=>x.id===id)}async function delFile(id){if(!fileDB)await openFileDB();return new Promise((res,rej)=>{const tx=fileDB.transaction('files','readwrite');tx.objectStore('files').delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function renderFiles(){fillOptions($('#fileCategory'),CATEGORIES);fillOptions($('#fileFilter'),CATEGORIES,true,'All Areas');$('#fileTask').innerHTML='<option value="">General / not linked</option>'+db.tasks.map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('');picked=[];$('#fileInput').onchange=e=>{picked.push(...e.target.files);$('#pickedFiles').innerHTML=picked.map(f=>`<span class="filechip">${esc(f.name)}</span>`).join('')};$('#saveFiles').onclick=saveFiles;$('#fileFilter').onchange=drawFiles;drawFiles()}async function saveFiles(){if(!picked.length){alert('Select file(s).');return}for(const f of picked)await putFile({id:uid(),category:$('#fileCategory').value,taskId:$('#fileTask').value,note:$('#fileNote').value,name:f.name,type:f.type,size:f.size,date:today(),blob:f});picked=[];$('#pickedFiles').innerHTML='';$('#fileInput').value='';drawFiles()}async function drawFiles(){const filter=$('#fileFilter')?.value||'',a=(await allFiles()).filter(f=>!filter||f.category===filter).reverse();$('#filesList').innerHTML=a.map(f=>`<div class="fileitem"><b>${esc(f.name)}</b><div class="tiny muted">${esc(f.category)} • ${fmt(f.date)} • ${Math.round(f.size/1024)} KB</div><div>${esc(f.note||'')}</div><div class="actionrow"><button class="ghost" onclick="app.openFile('${f.id}')">Open</button><button class="ghost" onclick="app.downloadFile('${f.id}')">Download</button><button class="ghost" onclick="app.removeFile('${f.id}')">Delete</button></div></div>`).join('')||'<p class="muted">No file.</p>'}async function openFile(id){const f=await getFile(id);if(f)window.open(URL.createObjectURL(f.blob),'_blank')}async function downloadFile(id){const f=await getFile(id);if(!f)return;const a=document.createElement('a');a.href=URL.createObjectURL(f.blob);a.download=f.name;a.click()}async function removeFile(id){if(confirm('Delete file?')){await delFile(id);drawFiles()}}
function renderBackup(){$('#backupBtn').onclick=()=>download('SAO-Workplace-backup-'+today()+'.json',JSON.stringify(db,null,2),'application/json');$('#restoreInput').onchange=async e=>{try{db=JSON.parse(await e.target.files[0].text());db.settings={...defaultSettings,...(db.settings||{})};db.reflections=db.reflections||[];db.tasks=db.tasks.map(t=>({estimatedMinutes:0,nextAction:'',waitingFor:'',waitingContact:'',repeat:'None',focus:false,progress:t.status==='Done'?100:0,...t}));save();alert('Restored.');showView('dashboard')}catch{alert('Invalid backup.')}};$('#csvBtn').onclick=()=>{const h=['Title','Area','Project','Priority','Status','Start Horizon','Start Date','Due Date','Reminder','Responsible','Context','Tags','Notes'];const rows=db.tasks.map(t=>[t.title,t.category,t.project,t.priority,t.status,t.horizon,t.startDate,t.dueDate,t.reminderDate,t.owner,t.context,t.tags,t.notes]);download('SAO-Workplace-tasks.csv',[h,...rows].map(r=>r.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}}function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click()}
function renderSettings(){
  $('#settingsForm').innerHTML=`<div class="formgrid"><label>App Name<input id="set_name" value="${esc(db.settings.appName)}"></label><label>Owner Name<input id="set_owner" value="${esc(db.settings.ownerName)}"></label><label>Daily Naam Japa Target<input id="set_japa" type="number" value="${db.settings.dailyJapaTarget}"></label><label>Week Starts<select id="set_week"><option>Monday</option><option ${db.settings.weekStarts==='Sunday'?'selected':''}>Sunday</option></select></label><label>Appearance<select id="set_theme"><option ${db.settings.theme!=='Dark'?'selected':''}>Soft Blue</option><option ${db.settings.theme==='Dark'?'selected':''}>Dark</option></select></label></div><div class="actionrow"><button id="saveSettings">Save Settings</button></div>`;
  $('#saveSettings').onclick=()=>{db.settings={...db.settings,appName:$('#set_name').value,ownerName:$('#set_owner').value,dailyJapaTarget:+$('#set_japa').value||5000,weekStarts:$('#set_week').value,theme:$('#set_theme').value};save();applyTheme();alert('Settings saved.')};
  $('#notificationState').textContent='Current permission: '+(window.Notification?Notification.permission:'Not supported');
  $('#notificationBtn').onclick=async()=>{if(!window.Notification){alert('Notifications not supported in this browser.');return}const p=await Notification.requestPermission();$('#notificationState').textContent='Current permission: '+p;if(p==='granted')new Notification('SAO Workplace',{body:'Notifications enabled. In-app due reminders will be shown while the app is active.'})};
}
function checkReminders(){const due=db.tasks.filter(t=>!isDone(t)&&t.reminderDate===today());if(!due.length)return;const key='sao_reminder_seen_'+today();if(sessionStorage.getItem(key))return;sessionStorage.setItem(key,'1');if(window.Notification&&Notification.permission==='granted')new Notification('SAO Workplace Reminder',{body:`${due.length} task${due.length===1?'':'s'} need attention today.`})}
function init(){applyTheme();openFileDB().catch(()=>{});$$('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('#quickAddBtn').onclick=openQuickAdd;$('#voiceQuickBtn').onclick=()=>{showView('ai');setTimeout(()=>startVoiceCapture('#aiCommandInput'),100)};$('#closeModal').onclick=closeQuick;$('#cancelQuick').onclick=closeQuick;$('#saveQuick').onclick=saveQuick;$('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){showView('tasks');$('#taskSearch').value=e.target.value;drawTasks()}};showView('dashboard')}
return{init,showView,openQuickAdd,openWorkspace,editTask,markDone,shareTask,deleteTask,editStudy,editTravel,openFile,downloadFile,removeFile,reschedule,startVoiceCapture};})();document.addEventListener('DOMContentLoaded',app.init);
